# .github/release.yml

changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
        - funky
    - title: Documentation Changes
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
