name: Add Reviewers on Pull Request

on:
  pull_request:
    branches: [main]
    # types: [opened, ready_for_review, reopened]
    
jobs: 
  add-reviewers:
    name: Add Pull Request Reviewers
    runs-on: windows-latest
    steps:
      - name: Add other team members
        if: ${{ contains(github.actor, 'lizzcondrey') }}
          echo 'found matching user'
          
      
