name: Update PR in Project
on:
  pull_request:
    types: [opened, reopened, ready_for_review, converted_to_draft]

jobs:
  project-draft-pr:
    if: ${{ github.event.pull_request.draft == true }}
    name: Update Project Item Draft PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update project fields
        uses: EndBug/project-fields@v2.0.2
        with:
          operation: set
          fields: Status
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_url: https://github.com/orgs/experiment-playground/projects/1
          resource_url: https://github.com/my-user/repo/pull/${{ github.event.pull_request.number }}
          values: In Progress
          
  project-pr-ready:
    if: ${{ github.event.pull_request.draft == false }}
    name: Update Project Item PR In Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update project fields
        uses: EndBug/project-fields@v2.0.2
        with:
          operation: set
          fields: Status
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_url: https://github.com/orgs/experiment-playground/projects/1
          resource_url: https://github.com/my-user/repo/pull/${{ github.event.pull_request.number }}
          values: In Review
          
  # project-pr-re-review:
  #   if: ${{ github.event.pull_request_review_thread. }}
  #   name: Update Project Item PR In Review For Re-Review
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #     - name: Update project fields
  #       uses: EndBug/project-fields@v2.0.2
  #       with:
  #         operation: set
  #         fields: Status
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         project_url: https://github.com/orgs/experiment-playground/projects/1
  #         resource_url: https://github.com/my-user/repo/pull/${{ github.event.pull_request.number }}
  #         values: In Review
