name: Notify on Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  send_notification:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.ref}}
      - name: Get Commit Messages
        run: |
         commit_messages=$(git log | git shortlog --maxcount=15)
         echo "pulled commits: ${commit_messages}"
